name: Collection build and tests

on:
  push:
  pull_request:
#  schedule:
#    - cron: 3 0 * * *  # Run daily at 0:03 UTC

jobs:
  openai-analysis:
    name: Build
    runs-on: ${{ matrix.runner-os }}
    strategy:
      matrix:
        runner-os:
          - ubuntu-22.04
        ansible-version:
          - git+https://github.com/ansible/ansible.git@stable-2.14
        runner-python-version:
          - 3.9
    steps:
      - name: Check out ${{ github.repository }} on disk
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.runner-python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.runner-python-version }}
      - name: Install Ansible ${{ matrix.ansible-version }} and openAI
        run: |
          python -m pip install --user '${{ matrix.ansible-version }}'
          python -m pip install --user openai
      - name: run openai analysis
        run: |
          ansible-galaxy collection install sshnaidm.openai
          cd tests/
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          ANSIBLE_CALLBACKS_ENABLED=sshnaidm.openai.openai ansible-playbook test.yml --check
          
          
        
