name: update collection

'on':
  pull_request:
  push:
    branches:
      - main

jobs:

  update:
    runs-on: ubuntu-latest
    steps:
    - name: retrieve collection code and update submodule
      run: |
        git clone https://github.com/eazytrainingfr/ansible-collection_webapp.git
        cd ansible-collection_webapp
        git submodule update --init --recursive
        cd roles/nginx
        git pull origin main
        cd ../..
        git add .
        git config --global user.email "eazytrainingfr@gmail.com"
        git config --global user.name "eazytrainingfr"
        git commit -m "update role nginx commit ${{ github.sha }}"
        git remote set-url origin https://eazytrainingfr:${secrets.API_TOKEN_GITHUB}@github.com/eazytrainingfr/ansible-collection_webapp.git
        git push origin main
